### ISSUE TITLE
glog-extras.cmake breaks my complation

### ISSUE THREAD

**Issue by prclibo** [ethz-asl/glog_catkin#9]
Hi,
I was compiling ethz_msf with glog_caktin but got a complation error. I find this question:

The `CFG_EXTRAS glog-extras.cmake` from [Line 28](https://github.com/ethz-asl/glog_catkin/blob/master/CMakeLists.txt#L28) changes `${glog_catkin_LIBRARIES}` from `glog_catkin` to `devel//lib/libglog.so`. However, in ethz_msf, cmake cannot finds how to make `libglog.so` with the following error:

    make[3]: *** No rule to make target `/home/li/catkin_ws/devel/lib/libglog.so', needed by `/home/li/catkin_ws/devel/lib/libsimilaritytransform.so'.  Stop.

If I remove `CFG_EXTRAS glog-extras.cmake` then everything compiles good. I am using Ubuntu 14.04, Indigo, CMake 2.8.12.2, with everything installed from `apt-get`. So just wanna quick question about this. Thank you:)

**Comment by prclibo** [comment]
@simonlynen thanks for the reply. I guess by `catkin build` you mean `catkin_make`. Yes, I can do `catkin_make glog_catkin`

My problem is that when compiling `ethz_msf` and `glog_catkin`, and also some other packages together, CMake wants to link `similaritytransform` to `libglog.so`. But `glog_catkin` doesnot define rule about how to make `libglog.so` (i.e. no target named libglog.so). `libglog.so` was compiled inside `ExternalProject_Add` and its rule is not passed to `ethz_msf`. So when `glog_catkin` is compiled before `ethz_msf`, then everything goes well, but when `ethz_msf` is somehow compiled before `glog_catkin`, which seems to be my case, the compilation will crash.

**Comment by simonlynen** [comment]
@prclibo ok, that is strange since this definitly works here with a clean workspace. Let me explain how this is intended to work:
-> external project add compiles libglog
-> we add a fake library called dependency-tracker in glog_catkin that we let depend on the external project.
-> once the external project is compiled (and lobglog exists) we link the dependency tracker to it.
-> in the cmake export file we now swap out the exported library (dependency tracker) with the libglog from the external project s.t. other packages like msf_core link to it.

We are building this library on a daily basis from scratch on a build-server, so I am surprised this doesn't work for you.

**Comment by furgalep** [comment]
Hi Bo!

One other thing. We discourage the use of catkin_make because it creates a single cmake invocation to build the whole workspace. This creates bugs. Subtle, hard-to-track-down, annoying bugs. CMake stuff. Impossible.

We use [catkin tools](http://catkin-tools.readthedocs.org/en/latest/) and since we switched, life got a lot better.

Please give it a try!

**Comment by prclibo** [comment]
Hey Paul!
Thanks for the recommendation. The catkin tools are really good tool. I am right now switching to it!

**Comment by prclibo** [comment]
@simonlynen Thanks for the explanation. By `catkin build` I can do the compilation good. But still I wanna further question about the reason of replacing the dependency tracker library (i.e. glog_catkin) with libglog.so. Can you please explain this? Because for me exporting glog_catkin seems more straightforward. It also seems ok for other packages to link to glog_catkin since glog_catkin is already linked to libglog.so

**Comment by simonlynen** [comment]
@prclibo the reason is that on some platforms the symbols of glog get stripped out of the dep tracker lib and thus not exported through it. This method has just proven to be the most reliable. Your suggestion would not solve the broken dependency tracking of catkin, that you reported.

**Comment by prclibo** [comment]
@simonlynen Yes, I understand it can be troublesome to make the compilation cross platforms, and thanks for the kind explanation.
